// GENERATED by fw from ui-spec/project.ts (tokens). Do not edit: every fw command rewrites it.
// Every value is a CSS custom property from ./tokens.css, so a mode switch restyles without a render.
// Use tokens.* in styles; alpha(tokens.color.primary, 0.12) for translucent colors; values.* only where a number is
// unavoidable (canvas, charts), and redraw on onModeChange().

export const tokens = {
  color: { primary: 'var(--ui-color-primary)', onPrimary: 'var(--ui-color-on-primary)', secondary: 'var(--ui-color-secondary)', onSecondary: 'var(--ui-color-on-secondary)', danger: 'var(--ui-color-danger)', onDanger: 'var(--ui-color-on-danger)', success: 'var(--ui-color-success)', onSuccess: 'var(--ui-color-on-success)', warning: 'var(--ui-color-warning)', onWarning: 'var(--ui-color-on-warning)', surface: 'var(--ui-color-surface)', surfaceAlt: 'var(--ui-color-surface-alt)', text: 'var(--ui-color-text)', muted: 'var(--ui-color-muted)', border: 'var(--ui-color-border)', scrim: 'var(--ui-color-scrim)', shadow: 'var(--ui-color-shadow)' },
  space: ['var(--ui-space-0)', 'var(--ui-space-1)', 'var(--ui-space-2)', 'var(--ui-space-3)', 'var(--ui-space-4)', 'var(--ui-space-5)', 'var(--ui-space-6)', 'var(--ui-space-7)'],
  radius: { sm: 'var(--ui-radius-sm)', md: 'var(--ui-radius-md)', lg: 'var(--ui-radius-lg)', full: 'var(--ui-radius-full)' },
  size: { controlSm: 'var(--ui-size-control-sm)', controlMd: 'var(--ui-size-control-md)', controlLg: 'var(--ui-size-control-lg)' },
  font: { body: 'var(--ui-font-body)', heading: 'var(--ui-font-heading)' },
  component: {  },
} as const;

/** Resolved values of the default mode (numbers, hex): for code that cannot use a CSS variable. */
export const values = {"color":{"primary":"#D12F0C","onPrimary":"#FFFFFF","secondary":"#3B4CCA","onSecondary":"#FFFFFF","danger":"#B91C1C","onDanger":"#FFFFFF","success":"#15803D","onSuccess":"#FFFFFF","warning":"#B45309","onWarning":"#FFFFFF","surface":"#FFFFFF","surfaceAlt":"#F3F4F6","text":"#1F2937","muted":"#6B7280","border":"#E5E7EB","scrim":"#000000","shadow":"#000000"},"space":[0,4,8,12,16,24,32,48],"radius":{"sm":4,"md":8,"lg":16,"full":9999},"size":{"controlSm":32,"controlMd":40,"controlLg":48},"font":{"body":"Inter","heading":"Inter"},"component":{}} as const;

/** spacing step: sp(4) → var(--ui-space-4) */
export const sp = (step: number | string): string => tokens.space[Math.min(Number(step), tokens.space.length - 1)] ?? tokens.space[0];
export const font = (which: keyof typeof tokens.font): string => tokens.font[which];
/** A token color at an opacity: alpha(tokens.color.primary, 0.12) → color-mix(in srgb, var(--ui-color-primary) 12%, transparent) */
export const alpha = (color: string, opacity: number): string => `color-mix(in srgb, ${color} ${Math.round(opacity * 100)}%, transparent)`;

export interface Mode {

}
export const defaultMode: Mode = {};
const KEY = 'ui-mode';
const attr = (axis: string) => 'data-ui-' + axis.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const listeners = new Set<(mode: Mode) => void>();

/** Current mode: what setMode() last applied, else the defaults (colorScheme 'system' follows the OS). */
export function getMode(): Mode {
  if (typeof document === 'undefined') return { ...defaultMode };
  const root = document.documentElement;
  return Object.fromEntries(Object.entries(defaultMode).map(([axis, d]) => [axis, root.getAttribute(attr(axis)) ?? d])) as unknown as Mode;
}

/** Switch one or more axes: setMode({ colorScheme: 'dark' }). Remembered in localStorage unless persist is false. */
export function setMode(mode: Partial<Mode>, options: { persist?: boolean } = {}): void {
  if (typeof document === 'undefined') return;
  const next = { ...getMode(), ...mode } as Mode;
  for (const [axis, value] of Object.entries(next)) document.documentElement.setAttribute(attr(axis), String(value));
  if (options.persist !== false) { try { localStorage.setItem(KEY, JSON.stringify(next)); } catch { /* storage unavailable */ } }
  listeners.forEach((l) => l(next));
}

/** Called after every setMode(); returns an unsubscribe function. */
export function onModeChange(listener: (mode: Mode) => void): () => void {
  listeners.add(listener);
  return () => { listeners.delete(listener); };
}

/** Put in <head> before the CSS (SSR / Next.js) so a remembered mode applies before the first paint: no flash. */
export const modeScript = `(function(){try{var m=JSON.parse(localStorage.getItem('${KEY}')||'{}');for(var k in m)document.documentElement.setAttribute('data-ui-'+k.replace(/([a-z0-9])([A-Z])/g,'$1-$2').toLowerCase(),m[k])}catch(e){}})()`;
