import ts from 'typescript';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, relative, basename } from 'node:path';
import { DIRS } from './loader.ts';

/**
 * fw add <file>: read an existing React component's props and write a minimal
 * contract into ui-spec/added/<Name>.rule.ts. The source file is not touched.
 * The generated contract has the same shape as a shipped one.
 */
export function addReactComponent(root: string, file: string, nameOverride?: string): { contractFile: string; name: string; todo: string[] } {
  const src = readFileSync(file, 'utf8');
  const sf = ts.createSourceFile(file, src, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const exportName = nameOverride ?? guessExport(sf) ?? basename(file).replace(/\.\w+$/, '');
  const name = nameOverride ?? exportName;
  const props = extractProps(sf, exportName);
  const todo: string[] = [];
  const lines: string[] = [];
  const events: string[] = [];
  for (const [k, m] of props) {
    const ev = k.match(/^on([A-Z]\w*)$/);
    if (ev) { events.push(`    ${ev[1][0].toLowerCase() + ev[1].slice(1)}: t.void(),`); continue; }
    const t = toT(m.typeText);
    if (!t) todo.push(`prop "${k}": type "${m.typeText}" could not be mapped — edit the contract by hand`);
    lines.push(`    ${k}: ${t ?? `t.string() /* TODO: was ${m.typeText} */`}${m.optional ? '.opt()' : ''},`);
  }
  const hasChildren = props.has('children');
  const contract = `import { defineComponent, t } from '@genui/core';

// Generated by \`fw add\` from ${relative(root, file)}. Edit freely: this file is yours.
export default defineComponent({
  name: '${name}',
  category: 'composite',
  purpose: 'TODO: what it is for, and what not to use it for.',
  props: {
${lines.filter((l) => !l.startsWith('    children:')).join('\n')}
  },${events.length ? `\n  events: {\n${events.join('\n')}\n  },` : ''}${hasChildren ? '\n  children: true,' : ''}
  rules: [],
  impl: { react: '${relative(root, file)}' },
});
`;
  const dir = join(root, DIRS.spec, 'added');
  mkdirSync(dir, { recursive: true });
  const out = join(dir, `${name}.rule.ts`);
  if (existsSync(out)) throw new Error(`${relative(root, out)} already exists`);
  writeFileSync(out, contract);
  return { contractFile: relative(root, out), name, todo };
}

function guessExport(sf: ts.SourceFile): string | null {
  let name: string | null = null;
  sf.forEachChild((n) => {
    if (name) return;
    const exp = !!(ts.getCombinedModifierFlags(n as ts.Declaration) & ts.ModifierFlags.Export);
    if (ts.isFunctionDeclaration(n) && exp && n.name && /^[A-Z]/.test(n.name.text)) name = n.name.text;
    if (ts.isVariableStatement(n) && exp) for (const d of n.declarationList.declarations) if (ts.isIdentifier(d.name) && /^[A-Z]/.test(d.name.text)) name = d.name.text;
  });
  return name;
}

function extractProps(sf: ts.SourceFile, exportName: string): Map<string, { optional: boolean; typeText: string }> {
  // reuse verify's approach in a compact form: find the first interface/type ending with Props, else first param literal
  const out = new Map<string, { optional: boolean; typeText: string }>();
  const collect = (members: ts.NodeArray<ts.TypeElement>) => {
    for (const m of members) if (ts.isPropertySignature(m) && m.name)
      out.set(m.name.getText(sf), { optional: !!m.questionToken, typeText: m.type?.getText(sf) ?? 'any' });
  };
  let done = false;
  sf.forEachChild((n) => {
    if (done) return;
    if (ts.isInterfaceDeclaration(n) && /Props$/.test(n.name.text)) { collect(n.members); done = true; }
    if (ts.isTypeAliasDeclaration(n) && /Props$/.test(n.name.text) && ts.isTypeLiteralNode(n.type)) { collect(n.type.members); done = true; }
  });
  if (!done) sf.forEachChild((n) => {
    if (done) return;
    if (ts.isFunctionDeclaration(n) && n.name?.text === exportName && n.parameters[0]?.type && ts.isTypeLiteralNode(n.parameters[0].type)) { collect(n.parameters[0].type.members); done = true; }
  });
  return out;
}

function toT(text: string): string | null {
  const t = text.replace(/\s+/g, ' ').trim();
  if (t === 'string') return 't.string()';
  if (t === 'number') return 't.number()';
  if (t === 'boolean') return 't.boolean()';
  const en = t.match(/^(['"][\w-]+['"](\s*\|\s*)?)+$/);
  if (en) return `t.enum([${t.split('|').map((s) => s.trim().replace(/"/g, "'")).join(', ')}])`;
  const arr = t.match(/^(\w+)\[\]$/);
  if (arr) { const inner = toT(arr[1]); return inner ? `t.array(${inner})` : `t.array(t.ref('${arr[1]}'))`; }
  if (/^[A-Z]\w*$/.test(t)) return `t.ref('${t}')`;
  if (/ReactNode/.test(t)) return 't.node()';
  return null;
}
