import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative } from 'node:path';
import type { Check, CheckActivation, CheckKey, CheckProps, CheckRole, CheckSize, ComponentContract, ProjectConfig } from './define.ts';
import type { TypeNode } from './types.ts';
import { checkLiteral } from './types.ts';
import { Report } from './diagnostics.ts';
import { callbackName, dartClass, enumType, enumValue, itemClass, snake } from './flutter.ts';
import { dartClasses, dartEnums, maskDart } from './dart.ts';

/**
 * Behavioural checks: contract `checks` → one generated test file per component and platform → run by the
 * platform's own runner (vitest / flutter test) → results back as a Report per file.
 * Only `fw verify` runs them; `fw check` stays static (validateChecks only).
 */

export type Platform = 'react' | 'flutter';
const KINDS = ['size', 'keepsSize', 'emits', 'neverEmits', 'role', 'key', 'rendersNothing', 'minTarget'];
const LAYOUT = new Set(['size', 'keepsSize', 'minTarget']);
const levelOf = (c: Check) => c.level ?? (c.kind === 'minTarget' ? 'warn' : 'error');
const GENERATED = 'GENERATED by fw verify';

export const testFile = (p: Platform, name: string) => (p === 'react' ? `test/fw/${name}.contract.test.tsx` : `test/fw/${snake(name)}_contract_test.dart`);

// ---------- static validation (fw check and fw verify) ----------

/** Every checks[i] must name real props / events / enum values, with values of the right type. */
export function validateChecks(c: ComponentContract, config: ProjectConfig, r: Report): void {
  (c.checks ?? []).forEach((ch, i) => {
    const at = `checks[${i}]`;
    if (!KINDS.includes(ch.kind)) { r.error(at, `unknown kind "${(ch as { kind: string }).kind}" (${KINDS.join(', ')})`); return; }
    const props = (p: CheckProps | undefined, where: string) => {
      for (const [k, v] of Object.entries(p ?? {})) {
        const ty = c.props[k];
        if (!ty) { r.error(`${at}.${where}.${k}`, `no prop "${k}" in the contract`); continue; }
        if (ty.kind === 'node') continue;
        if (v === null) { if (!ty.optional) r.error(`${at}.${where}.${k}`, 'null leaves the prop out, but it is required'); continue; }
        const e = checkLiteral(v, ty);
        if (e) r.error(`${at}.${where}.${k}`, e);
      }
    };
    const event = (e: string, where: string) => { if (!c.events?.[e]) r.error(`${at}.${where}`, `no event "${e}" in the contract`); };
    props(ch.props, 'props');
    switch (ch.kind) {
      case 'size': {
        const ty = c.props[ch.byProp];
        if (!ty || ty.kind !== 'enum') { r.error(`${at}.byProp`, `"${ch.byProp}" is not an enum prop of the contract`); break; }
        if (!ch.height && !ch.width) r.error(at, 'give height and/or width');
        for (const dim of ['height', 'width'] as const) for (const [v, s] of Object.entries(ch[dim] ?? {})) {
          if (!ty.values!.includes(v)) r.error(`${at}.${dim}.${v}`, `"${v}" is not a value of ${ch.byProp} (${ty.values!.join(', ')})`);
          if (resolveSize(s, config) === null) r.error(`${at}.${dim}.${v}`, `token "${(s as { token: string }).token}" is not a number in ui-spec/project.ts tokens`);
        }
        break;
      }
      case 'keepsSize': props(ch.like, 'like'); break;
      case 'emits': case 'neverEmits': event(ch.event, 'event'); break;
      case 'key': event(ch.emits, 'emits'); break;
      case 'role': if (ch.name && typeof ch.name === 'object' && !c.props[ch.name.fromProp]) r.error(`${at}.name.fromProp`, `no prop "${ch.name.fromProp}" in the contract`); break;
    }
  });
}

function resolveSize(s: CheckSize, config: ProjectConfig): number | null {
  if (typeof s === 'number') return s;
  let v: unknown = config.tokens;
  for (const part of s.token.split('.')) v = v && typeof v === 'object' ? (v as Record<string, unknown>)[part] : undefined;
  return typeof v === 'number' ? v : null;
}

// ---------- props for one render ----------

const cap = (s: string) => s[0].toUpperCase() + s.slice(1);

/** examples[0] + the check's props, with every required prop filled. Defaults are left to the component. */
function renderProps(c: ComponentContract, extra: CheckProps = {}): CheckProps {
  const out: CheckProps = { ...(c.examples?.[0] ?? {}), ...extra };
  for (const [k, v] of Object.entries(out)) if (v === null) delete out[k]; // null in a check = leave the prop out
  for (const [k, ty] of Object.entries(c.props)) {
    if (out[k] === undefined && !ty.optional) out[k] = placeholder(k, ty);
    else if (out[k] !== undefined) out[k] = complete(out[k], ty, k);
  }
  return out;
}
function placeholder(k: string, ty: TypeNode): unknown {
  switch (ty.kind) {
    case 'string': case 'node': return cap(k);
    case 'number': return 1;
    case 'boolean': return false;
    case 'enum': return ty.values![0];
    case 'array': return [];
    case 'object': return complete({}, ty, k);
    default: return {};
  }
}
function complete(v: unknown, ty: TypeNode, k: string): unknown {
  if (ty.kind === 'array' && Array.isArray(v)) return v.map((x) => complete(x, ty.of!, k));
  if (ty.kind === 'object' && v && typeof v === 'object') {
    const o = { ...(v as Record<string, unknown>) };
    for (const [f, fty] of Object.entries(ty.fields ?? {})) {
      if (o[f] === undefined && !fty.optional) o[f] = placeholder(f, fty);
      else if (o[f] !== undefined) o[f] = complete(o[f], fty, f);
    }
    return o;
  }
  return v;
}
function nameFor(ch: Extract<Check, { kind: 'role' }>, c: ComponentContract): string | undefined {
  if (!ch.name) return undefined;
  if (typeof ch.name === 'string') return ch.name;
  return String(renderProps(c, ch.props)[ch.name.fromProp]);
}

const title = (i: number, ch: Check) => {
  const d = ch.kind === 'size' ? `size by ${ch.byProp}`
    : ch.kind === 'emits' ? `emits ${ch.event} on ${(ch.on ?? ['press']).join('/')}`
    : ch.kind === 'neverEmits' ? `never emits ${ch.event} when ${JSON.stringify(ch.props)}`
    : ch.kind === 'role' ? `role ${ch.role}${ch.name ? ' with its accessible name' : ''}`
    : ch.kind === 'key' ? `${ch.key} emits ${ch.emits}`
    : ch.kind === 'keepsSize' ? `keeps size: ${JSON.stringify(ch.props)} like ${JSON.stringify(ch.like)}`
    : ch.kind === 'rendersNothing' ? `renders nothing when ${JSON.stringify(ch.props)}`
    : `pointer target at least ${ch.size}`;
  return `checks[${i}] ${d}`.replace(/'/g, '');
};

// ---------- React (vitest + Testing Library, jsdom) ----------

function tsVal(v: unknown, ty: TypeNode | undefined): string {
  if (ty?.kind === 'node') return `<span>{${JSON.stringify(String(v))}}</span>`;
  if (ty?.kind === 'array' && Array.isArray(v)) return `[${v.map((x) => tsVal(x, ty.of)).join(', ')}]`;
  if (ty?.kind === 'object' && v && typeof v === 'object') return `{ ${Object.entries(v).map(([k, x]) => `${JSON.stringify(k)}: ${tsVal(x, ty.fields?.[k])}`).join(', ')} }`;
  return JSON.stringify(v);
}
const USER_KEY: Record<CheckKey, string> = { Escape: '{Escape}', Enter: '{Enter}', Space: ' ', ArrowUp: '{ArrowUp}', ArrowDown: '{ArrowDown}', ArrowLeft: '{ArrowLeft}', ArrowRight: '{ArrowRight}', Home: '{Home}', End: '{End}' };

export function generateReactTest(c: ComponentContract, implFile: string, testPath: string): string {
  let imp = relative(dirname(testPath), implFile).replace(/\.(tsx|ts|jsx|js)$/, '').replace(/\/index$/, '');
  if (!imp.startsWith('.')) imp = `./${imp}`;
  const el = (extra: CheckProps | undefined, handler?: string) => {
    const p = renderProps(c, extra);
    const attrs = Object.entries(p).map(([k, v]) => `${JSON.stringify(k)}: ${tsVal(v, c.props[k])}`);
    const h = handler ? ` ${handler}={fn}` : '';
    return c.children ? `<${c.name} {...{ ${attrs.join(', ')} }}${h}><span>Child content</span></${c.name}>` : `<${c.name} {...{ ${attrs.join(', ')} }}${h} />`;
  };
  const act = (on: CheckActivation, target?: string) => on === 'press' ? `  await u.click(${target ? `screen.getByText(${JSON.stringify(target)})` : 'first(container)'});`
    : `  (document.activeElement as HTMLElement | null)?.blur();\n  await u.tab();\n  await u.keyboard(${JSON.stringify(on === 'enter' ? '{Enter}' : ' ')});`;
  const tests = (c.checks ?? []).map((ch, i) => {
    const name = title(i, ch);
    const tgt = (ch as { target?: string }).target;
    if (LAYOUT.has(ch.kind)) return `it.skip(${JSON.stringify(`${name} (needs browser: jsdom has no layout)`)}, () => {});`;
    const itR = levelOf(ch) === 'warn' ? 'it.skipIf(!(globalThis as { process?: { env: Record<string, string | undefined> } }).process?.env.FW_VERIFY)' : 'it';
    switch (ch.kind) {
      case 'emits': case 'neverEmits': {
        const ons = ch.on ?? ['press'];
        const expectR = (o: CheckActivation, n: number) => `  expect(fn, ${JSON.stringify(`after ${o}`)})${ch.kind === 'emits' ? `.toHaveBeenCalledTimes(${n})` : '.not.toHaveBeenCalled()'};`;
        return `${itR}(${JSON.stringify(name)}, async () => {\n  const fn = vi.fn();\n  const u = userEvent.setup({ pointerEventsCheck: 0 });\n  const { container } = render(${el(ch.props, callbackName(ch.event))});\n${ons.map((o, n) => `${act(o, tgt)}\n${expectR(o, n + 1)}`).join('\n')}\n});`;
      }
      case 'role': {
        const nm = nameFor(ch, c);
        return `${itR}(${JSON.stringify(name)}, () => {\n  render(${el(ch.props)});\n  expect(screen.getAllByRole(${JSON.stringify(ch.role)}${nm !== undefined ? `, { name: ${JSON.stringify(nm)} }` : ''}).length).toBeGreaterThan(0);\n});`;
      }
      case 'key':
        return `${itR}(${JSON.stringify(name)}, async () => {\n  const fn = vi.fn();\n  const u = userEvent.setup();\n  render(${el(ch.props, callbackName(ch.emits))});\n  await u.tab();\n  await u.keyboard(${JSON.stringify(USER_KEY[ch.key])});\n  expect(fn).toHaveBeenCalled();\n});`;
      case 'rendersNothing':
        return `${itR}(${JSON.stringify(name)}, () => {\n  const { container } = render(${el(ch.props)});\n  expect(container.childElementCount).toBe(0);\n  expect(document.body.childElementCount).toBe(1);\n});`;
    }
    return '';
  });
  return `// ${GENERATED} from the ${c.name} contract. Do not edit: change the contract's checks instead.
// @vitest-environment jsdom
import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { ${c.name} } from '${imp}';

afterEach(cleanup);
const first = (c: HTMLElement) => (c.firstElementChild as HTMLElement | null) ?? document.body;
void first; void screen; void vi; void userEvent;

${tests.join('\n\n')}
`;
}

// ---------- Flutter (flutter_test) ----------

const dstr = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$').replace(/\n/g, '\\n')}'`;
function dartVal(v: unknown, ty: TypeNode, comp: string, field: string, inArray = false): string {
  switch (ty.kind) {
    case 'enum': return `${enumType(comp, field)}.${enumValue(String(v))}`;
    case 'string': return dstr(String(v));
    case 'number': return ty.integer ? String(Math.round(Number(v))) : Number.isInteger(v) ? `${v}.0` : String(v);
    case 'boolean': return String(!!v);
    case 'node': return `const Text(${dstr(String(v))})`;
    case 'array': return `[${(v as unknown[]).map((x) => dartVal(x, ty.of!, comp, field, true)).join(', ')}]`;
    case 'object': {
      const o = v as Record<string, unknown>;
      return `${itemClass(comp, field, inArray)}(${Object.entries(ty.fields ?? {}).filter(([k]) => o[k] !== undefined).map(([k, f]) => `${k}: ${dartVal(o[k], f, comp, k)}`).join(', ')})`;
    }
    default: return 'const <String, Object?>{}';
  }
}
const ROLE_FLAGS: Partial<Record<CheckRole, string[]>> = {
  button: ['isButton'], link: ['isLink'], checkbox: ['hasCheckedState'], switch: ['hasToggledState'], radio: ['hasCheckedState', 'isInMutuallyExclusiveGroup'],
  textbox: ['isTextField'], slider: ['isSlider'], heading: ['isHeader'], img: ['isImage'], dialog: ['scopesRoute'], alertdialog: ['scopesRoute'], searchbox: ['isTextField'], status: ['isLiveRegion'], alert: ['isLiveRegion'],
};
const DART_KEY: Record<CheckKey, string> = { Escape: 'escape', Enter: 'enter', Space: 'space', ArrowUp: 'arrowUp', ArrowDown: 'arrowDown', ArrowLeft: 'arrowLeft', ArrowRight: 'arrowRight', Home: 'home', End: 'end' };

export function generateFlutterTest(c: ComponentContract, pkg: string, config: ProjectConfig): string {
  const cls = dartClass(c.name);
  const widget = (extra: CheckProps | undefined, event?: string) => {
    const p = renderProps(c, extra);
    const args = Object.entries(p).filter(([k]) => c.props[k]).map(([k, v]) => `${k}: ${dartVal(v, c.props[k], c.name, k)}`);
    if (event) args.push(`${callbackName(event)}: ${c.events![event].kind === 'void' ? '() => calls++' : '(_) => calls++'}`);
    if (c.children) args.push(`children: const [Text('Child content')]`);
    return `${cls}(${args.join(', ')})`;
  };
  const find = `find.byType(${cls})`;
  const shown = `_shown(tester, ${find})`; // the widget, or what it draws in an overlay when it lifts itself out of the layout
  const act = (on: CheckActivation, target?: string) => on === 'press'
    ? (target ? `    await _tapText(tester, ${dstr(target)});` : `    await tester.tap(${shown}, warnIfMissed: false);`) + `\n    await tester.pump();`
    : `    FocusManager.instance.primaryFocus?.unfocus();\n    await tester.pump();\n    await tester.sendKeyEvent(LogicalKeyboardKey.tab);\n    await tester.pump();\n    await tester.sendKeyEvent(LogicalKeyboardKey.${on === 'enter' ? 'enter' : 'space'});\n    await tester.pump();`;
  const tests = (c.checks ?? []).map((ch, i) => {
    const name = dstr(title(i, ch));
    const tgt = (ch as { target?: string }).target;
    const body = (() => {
      switch (ch.kind) {
        case 'size': {
          const lines: string[] = [];
          const values = new Set([...Object.keys(ch.height ?? {}), ...Object.keys(ch.width ?? {})]);
          for (const v of values) {
            lines.push(`    await tester.pumpWidget(_host(${widget({ ...ch.props, [ch.byProp]: v })}));`, `    await tester.pump();`, `    size = tester.getSize(${shown});`);
            if (ch.height?.[v] !== undefined) lines.push(`    expect(size.height, moreOrLessEquals(${resolveSize(ch.height[v], config)}.0, epsilon: 0.5), reason: ${dstr(`${ch.byProp}=${v} height`)});`);
            if (ch.width?.[v] !== undefined) lines.push(`    expect(size.width, moreOrLessEquals(${resolveSize(ch.width[v], config)}.0, epsilon: 0.5), reason: ${dstr(`${ch.byProp}=${v} width`)});`);
          }
          return `    Size size;\n${lines.join('\n')}`;
        }
        case 'keepsSize':
          return `    await tester.pumpWidget(_host(${widget(ch.like)}));\n    await tester.pump();\n    final before = tester.getSize(${shown});\n    await tester.pumpWidget(_host(${widget(ch.props)}));\n    await tester.pump();\n    await tester.pump(const Duration(milliseconds: 50));\n    final after = tester.getSize(${shown});\n    expect(after.width, moreOrLessEquals(before.width, epsilon: 0.5), reason: 'width');\n    expect(after.height, moreOrLessEquals(before.height, epsilon: 0.5), reason: 'height');`;
        case 'minTarget':
          return `    await tester.pumpWidget(_host(${widget(ch.props)}));\n    await tester.pump();\n    final size = tester.getSize(${shown});\n    expect(size.width, greaterThanOrEqualTo(${ch.size} - 0.5));\n    expect(size.height, greaterThanOrEqualTo(${ch.size} - 0.5));`;
        case 'emits': case 'neverEmits': {
          const ons = ch.on ?? ['press'];
          return `    var calls = 0;\n    await tester.pumpWidget(_host(${widget(ch.props, ch.event)}));\n    await tester.pump();\n${ons.map((o, n) => `${act(o, tgt)}\n    expect(calls, ${ch.kind === 'emits' ? n + 1 : 0}, reason: 'after ${o}');`).join('\n')}`;
        }
        case 'role': {
          const flags = ROLE_FLAGS[ch.role];
          if (!flags) return null;
          const nm = nameFor(ch, c);
          const cond = [...flags.map((f) => `d.hasFlag(SemanticsFlag.${f})`), ...(nm !== undefined ? [`(d.label.contains(${dstr(nm)}) || d.tooltip.contains(${dstr(nm)}))`] : [])].join(' && ');
          return `    final handle = tester.ensureSemantics();\n    await tester.pumpWidget(_host(${widget(ch.props)}));\n    await tester.pump();\n    expect(_semantics(tester, (d) => ${cond}), isTrue, reason: 'no semantics node with role ${ch.role}${nm !== undefined ? ` named ${nm.replace(/'/g, '')}` : ''}');\n    handle.dispose();`;
        }
        case 'key':
          return `    var calls = 0;\n    await tester.pumpWidget(_host(${widget(ch.props, ch.emits)}));\n    await tester.pump();\n    await tester.pump();\n    await tester.sendKeyEvent(LogicalKeyboardKey.tab);\n    await tester.pump();\n    await tester.sendKeyEvent(LogicalKeyboardKey.${DART_KEY[ch.key]});\n    await tester.pump();\n    expect(calls, greaterThan(0));`;
        case 'rendersNothing':
          return `    await tester.pumpWidget(_host(${widget(ch.props)}));\n    await tester.pump();\n    await tester.pump();\n    expect(find.descendant(of: ${find}, matching: find.byWidgetPredicate((w) => w is RichText || w is EditableText || w is Image || w is Icon)), findsNothing);\n    final size = tester.getSize(${find});\n    expect(size.width * size.height, 0);`;
      }
    })();
    return body === null
      ? `  testWidgets(${dstr(`${title(i, ch)} (skipped: no Flutter semantics flag for role ${(ch as { role: string }).role})`)}, (tester) async {}, skip: true);`
      : `  testWidgets(${name}, (tester) async {\n${body}\n  }${levelOf(ch) === 'warn' ? ', skip: !_fwVerify' : ''});`;
  });
  return `// ${GENERATED} from the ${c.name} contract. Do not edit: change the contract's checks instead.
// ignore_for_file: unused_import, unnecessary_import, unused_element, deprecated_member_use
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:${pkg}/ui/ui.dart';

// warn-level checks run only under fw verify, so a plain \`flutter test\` stays green on them
const _fwVerify = bool.fromEnvironment('FW_VERIFY');

Widget _host(Widget child) => MaterialApp(home: Scaffold(body: Align(alignment: Alignment.topLeft, child: child)));

// tap the text itself (reaches a link span inside a longer paragraph); text whose paragraph is not the hit target
// (a label inside a button) is tapped as a widget instead
Future<void> _tapText(WidgetTester tester, String text) async {
  try {
    await tester.tapOnText(find.textRange.ofSubstring(text));
  } on FlutterError {
    await tester.tap(find.text(text, findRichText: true).first, warnIfMissed: false);
  }
}

// A widget that draws through an OverlayPortal has no size of its own. Its drawn content is then the first descendant
// box that does not span (nearly) the whole screen in either direction: SafeArea / Padding / Align layers are skipped.
Finder _shown(WidgetTester tester, Finder widget) {
  if (!tester.getSize(widget).isEmpty) return widget;
  final screen = tester.view.physicalSize / tester.view.devicePixelRatio;
  for (final e in find.descendant(of: widget, matching: find.byWidgetPredicate((_) => true)).evaluate()) {
    final r = e.renderObject;
    if (r is RenderBox && r.hasSize && !r.size.isEmpty && r.size.width < screen.width * 0.9 && r.size.height < screen.height * 0.9) {
      return find.byElementPredicate((x) => x == e);
    }
  }
  return widget;
}

bool _semantics(WidgetTester tester, bool Function(SemanticsData d) test) {
  var found = false;
  void visit(SemanticsNode n) {
    if (test(n.getSemanticsData())) found = true;
    n.visitChildren((c) { visit(c); return true; });
  }
  for (final view in tester.binding.renderViews) {
    final root = view.owner?.semanticsOwner?.rootSemanticsNode;
    if (root != null) visit(root);
  }
  return found;
}

void main() {
${tests.join('\n\n')}
}
`;
}

// ---------- write + run ----------

export interface Target { contract: ComponentContract; implFile: string }

/** Generate test files for these components, remove generated files of components that no longer have checks, run the platform runner. */
export function runChecks(root: string, platform: Platform, config: ProjectConfig, targets: Target[], all: boolean): Report[] {
  const dir = join(root, 'test', 'fw');
  const withChecks = targets.filter((t) => t.contract.checks?.length);
  const files = withChecks.map((t) => testFile(platform, t.contract.name));
  if (all && existsSync(dir)) {
    for (const f of readdirSync(dir)) {
      const rel = `test/fw/${f}`;
      const ours = platform === 'react' ? f.endsWith('.contract.test.tsx') : f.endsWith('_contract_test.dart');
      if (ours && !files.includes(rel) && readFileSync(join(dir, f), 'utf8').includes(GENERATED)) rmSync(join(dir, f));
    }
  }
  if (!withChecks.length) return [];
  mkdirSync(dir, { recursive: true });
  const pkg = platform === 'flutter' ? pubspecName(root) : '';
  for (const t of withChecks) {
    const rel = testFile(platform, t.contract.name);
    writeFileSync(join(root, rel), platform === 'react' ? generateReactTest(t.contract, join(root, t.implFile), join(root, rel)) : registeredDart(root, t, pkg, generateFlutterTest(t.contract, pkg, config)));
  }
  const outcome = platform === 'react' ? runVitest(root, files) : runFlutter(root, files);
  return withChecks.map((t, n) => {
    const r = new Report(files[n]);
    const res = outcome.byFile.get(files[n]);
    if (outcome.fatal) { r.error('runner', outcome.fatal); return r; }
    if (!res) { r.error('runner', 'no results for this file'); return r; }
    if (res.loadError) { r.error('file', `test file failed to load: ${res.loadError}`); return r; }
    const skipped: number[] = [];
    t.contract.checks!.forEach((ch, i) => {
      const got = res.tests.get(i);
      if (!got) { r.error(`checks[${i}]`, 'no result (test did not run)'); return; }
      if (got.status === 'skipped') { skipped.push(i); return; }
      if (got.status === 'failed') {
        const msg = `${ch.kind} failed${ch.note ? ` (${ch.note})` : ''}: ${got.message}`;
        levelOf(ch) === 'error' ? r.error(`checks[${i}]`, msg) : r.warn(`checks[${i}]`, msg);
      }
    });
    if (skipped.length) r.warn(`checks[${skipped.join(',')}]`, platform === 'react' ? 'skipped on react: needs a browser (jsdom has no layout); checked on Flutter' : 'skipped on flutter (see the test name)');
    return r;
  });
}

interface FileResult { loadError?: string; tests: Map<number, { status: 'passed' | 'failed' | 'skipped'; message: string }> }
interface Outcome { fatal?: string; byFile: Map<string, FileResult> }
const indexOf = (testName: string) => Number(/checks\[(\d+)\]/.exec(testName)?.[1] ?? -1);
const clip = (s: string) => s.replace(/\u001b\[[0-9;]*m/g, '').split('\n').map((l) => l.trim()).filter((l) => l && !/^at |^(package:|dart:)|^#\d+|^Test failed\. See exception logs|^The test description was/.test(l)).slice(0, 4).join(' / ').slice(0, 400);

/**
 * A widget registered with fw add lives outside lib/ui/ and keeps its own names: import its file instead of the
 * barrel, and rename Ui<Name> / Ui<Name><Field> to the class and the enums (matched by their values) in that file.
 */
function registeredDart(root: string, t: Target, pkg: string, test: string): string {
  if (t.implFile.startsWith('lib/ui/')) return test;
  const m = maskDart(readFileSync(join(root, t.implFile), 'utf8'));
  const rename = new Map<string, string>();
  const name = t.contract.name;
  if (!dartClasses(m).some((x) => x.name === dartClass(name))) rename.set(dartClass(name), name);
  const enums = dartEnums(m);
  for (const [k, ty] of Object.entries(t.contract.props)) if (ty.kind === 'enum' && !enums.has(enumType(name, k))) {
    const same = [...enums].find(([, vs]) => vs.length === ty.values!.length && ty.values!.every((v) => vs.includes(enumValue(v))));
    if (same) rename.set(enumType(name, k), same[0]);
  }
  return test.replace(`import 'package:${pkg}/ui/ui.dart';`, `import 'package:${pkg}/${t.implFile.replace(/^lib\//, '')}';`).replace(/\bUi\w+\b/g, (n) => rename.get(n) ?? n);
}

function pubspecName(root: string): string {
  const f = join(root, 'pubspec.yaml');
  return existsSync(f) ? /^name:\s*(\S+)/m.exec(readFileSync(f, 'utf8'))?.[1] ?? 'app' : 'app';
}

function findUp(root: string, rel: string): string | null {
  for (let d = root; ; d = dirname(d)) {
    if (existsSync(join(d, rel))) return join(d, rel);
    if (dirname(d) === d) return null;
  }
}

function runVitest(root: string, files: string[]): Outcome {
  const bin = findUp(root, 'node_modules/.bin/vitest');
  // package.json is not always exported, so look for the folder the way Node's resolution walks up
  const missing = ['vitest', '@testing-library/react', '@testing-library/user-event', 'jsdom'].filter((m) => !findUp(root, `node_modules/${m}/package.json`));
  if (!bin || missing.length) return { fatal: `behavioural checks need ${missing.join(', ') || 'vitest'}: npm i -D vitest jsdom @testing-library/react @testing-library/user-event`, byFile: new Map() };
  const out = join(mkdtempSync(join(tmpdir(), 'fw-')), 'vitest.json');
  // A project without its own vite / vitest config gets a minimal one (automatic JSX runtime, jsdom), written next to the generated tests.
  const own = ['vitest.config', 'vite.config'].some((b) => ['ts', 'mts', 'js', 'mjs', 'cjs', 'cts'].some((e) => existsSync(join(root, `${b}.${e}`))));
  const config: string[] = [];
  if (!own) {
    writeFileSync(join(root, 'test', 'fw', 'vitest.config.mjs'), `// ${GENERATED}: used only when the project has no vite / vitest config of its own.
import { fileURLToPath } from 'node:url';
export default { root: fileURLToPath(new URL('../..', import.meta.url)), esbuild: { jsx: 'automatic' }, test: { environment: 'jsdom', include: ['test/fw/**/*.test.tsx'] } };
`);
    config.push('--config', 'test/fw/vitest.config.mjs');
  }
  const run = spawnSync(bin, ['run', ...config, '--reporter=json', `--outputFile=${out}`, ...files], { cwd: root, encoding: 'utf8', env: { ...process.env, FW_VERIFY: '1' } });
  if (!existsSync(out)) return { fatal: `vitest did not report: ${clip(run.stderr || run.stdout || String(run.error))}. Make sure the vitest config includes test/fw/**`, byFile: new Map() };
  const json = JSON.parse(readFileSync(out, 'utf8')) as { testResults: { name: string; message?: string; assertionResults: { title: string; status: string; failureMessages: string[] }[] }[] };
  const byFile = new Map<string, FileResult>();
  for (const tr of json.testResults) {
    const rel = relative(root, tr.name);
    const fr: FileResult = { tests: new Map() };
    if (!tr.assertionResults.length && tr.message) fr.loadError = clip(tr.message);
    for (const a of tr.assertionResults) fr.tests.set(indexOf(a.title), { status: a.status === 'passed' ? 'passed' : a.status === 'failed' ? 'failed' : 'skipped', message: clip(a.failureMessages.join('\n')) });
    byFile.set(rel, fr);
  }
  return { byFile };
}

function runFlutter(root: string, files: string[]): Outcome {
  const args = ['test', '--reporter', 'json', '--dart-define=FW_VERIFY=true', ...(existsSync(join(root, '.dart_tool', 'package_config.json')) ? ['--no-pub'] : []), ...files];
  const run = spawnSync('flutter', args, { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  if (run.error) return { fatal: `could not run flutter (${(run.error as NodeJS.ErrnoException).code ?? run.error.message}): install the Flutter SDK and put it on PATH`, byFile: new Map() };
  const byFile = new Map<string, FileResult>();
  const suites = new Map<number, string>(), tests = new Map<number, { file: string; name: string }>(), errors = new Map<number, string[]>();
  for (const line of run.stdout.split('\n')) {
    if (!line.startsWith('{')) continue;
    let e: Record<string, any>; try { e = JSON.parse(line); } catch { continue; }
    if (e.type === 'suite') { const rel = relative(root, e.suite.path); suites.set(e.suite.id, rel); byFile.set(rel, byFile.get(rel) ?? { tests: new Map() }); }
    if (e.type === 'testStart') tests.set(e.test.id, { file: suites.get(e.test.suiteID) ?? '', name: e.test.name });
    if (e.type === 'error') errors.set(e.testID, [...(errors.get(e.testID) ?? []), e.error]);
    // flutter_test prints the real failure (Expected / Actual / reason) and reports only "Test failed" as the error
    if (e.type === 'print' && typeof e.message === 'string' && e.message.includes('EXCEPTION CAUGHT')) {
      const m = /was thrown (?:running a test|while running async test code):\n([\s\S]*?)\n\n(?:When the exception|The test description)/.exec(e.message);
      if (m) errors.set(e.testID, [m[1], ...(errors.get(e.testID) ?? [])]);
    }
    if (e.type === 'testDone' && !e.hidden) {
      const t = tests.get(e.testID); if (!t) continue;
      const fr = byFile.get(t.file)!;
      const i = indexOf(t.name);
      if (i < 0) { if (e.result !== 'success') fr.loadError = clip((errors.get(e.testID) ?? []).join('\n') || t.name); continue; }
      fr.tests.set(i, { status: e.skipped ? 'skipped' : e.result === 'success' ? 'passed' : 'failed', message: clip((errors.get(e.testID) ?? []).join('\n')) });
    }
    if (e.type === 'testDone' && e.hidden && e.result !== 'success') {
      const t = tests.get(e.testID); if (t) byFile.get(t.file)!.loadError = clip((errors.get(e.testID) ?? []).join('\n'));
    }
  }
  for (const f of files) if (!byFile.has(f)) byFile.set(f, { loadError: clip(run.stderr || run.stdout) || 'did not run', tests: new Map() });
  return { byFile };
}
