// Web output of the theme model: ui/tokens.css (CSS custom properties per mode) and ui/tokens.g.ts (typed accessors that
// point at those properties, plus mode switching). Switching a mode flips data attributes on <html>; the browser
// restyles without a React render. Pure string generation, browser-safe.
import { modeAxes, normalizeTokens, resolveTheme, type ModeSelection, type ProjectTokens, type ThemeTokens, type TokenOverrides } from './theme.ts';

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/\./g, '-').toLowerCase();
const stack = (f: string) => (/,/.test(f) ? f : `${f}, system-ui, sans-serif`);
export const cssVar = (path: string) => `--ui-${kebab(path)}`;
const HEADER = (what: string) => `GENERATED by fw from ui-spec/project.ts (${what}). Do not edit: every fw command rewrites it.`;

type Group = 'color' | 'space' | 'radius' | 'size' | 'font' | 'component';
interface Entry { path: string; value: unknown; group: Group }

/** Every semantic / component token of one layer as [path, raw value]: color.primary, space.4, component.button.primaryBg. */
function entries(layer: TokenOverrides): Entry[] {
  const out: Entry[] = [];
  for (const [k, v] of Object.entries(layer.color ?? {})) out.push({ path: `color.${k}`, value: v, group: 'color' });
  (layer.space ?? []).forEach((v, i) => { if (v !== undefined) out.push({ path: `space.${i}`, value: v, group: 'space' }); });
  for (const [k, v] of Object.entries(layer.radius ?? {})) out.push({ path: `radius.${k}`, value: v, group: 'radius' });
  for (const [k, v] of Object.entries(layer.size ?? {})) out.push({ path: `size.${k}`, value: v, group: 'size' });
  for (const [k, v] of Object.entries(layer.font ?? {})) out.push({ path: `font.${k}`, value: v, group: 'font' });
  for (const [c, vs] of Object.entries(layer.component ?? {})) for (const [k, v] of Object.entries(vs)) out.push({ path: `component.${c}.${k}`, value: v, group: 'component' });
  return out;
}

/**
 * The CSS value of one token. A reference to another semantic / component token becomes var(--…) so it follows every
 * mode on its own; a reference to a primitive (or a literal) becomes the resolved value.
 */
function cssValue(t: ThemeTokens, e: Entry, sel: ModeSelection): string {
  const semanticGroups = ['color', 'space', 'radius', 'size', 'font', 'component'];
  const v = e.value;
  if (typeof v === 'string' && /^\{[\w.-]+\}$/.test(v)) {
    const path = v.slice(1, -1);
    const [group, ...rest] = path.split('.');
    const inSemantic = semanticGroups.includes(group) && definedInSemantic(t, group, rest);
    if (inSemantic) return `var(${cssVar(path)})`;
  }
  const r = resolveTheme(t, sel).theme as unknown as Record<string, unknown>;
  let x: unknown = r[e.group];
  for (const p of e.path.split('.').slice(1)) x = x && typeof x === 'object' ? (x as Record<string, unknown>)[p] : undefined;
  if (typeof x === 'number') return e.group === 'component' && /opacity|weight|z/i.test(e.path) ? String(x) : `${x}px`;
  if (e.group === 'font' && typeof x === 'string') return stack(x);
  return String(x ?? '');
}

function definedInSemantic(t: ThemeTokens, group: string, rest: string[]): boolean {
  let v: unknown = (t.semantic as unknown as Record<string, unknown>)[group];
  for (const p of rest) v = v && typeof v === 'object' ? (v as Record<string, unknown>)[p] : undefined;
  return v !== undefined;
}

const block = (selector: string, lines: string[], indent = '') => (lines.length ? `${indent}${selector} {\n${lines.map((l) => `${indent}  ${l}`).join('\n')}\n${indent}}\n` : '');

/** ui/tokens.css */
export function tokensCss(tokens: ProjectTokens): string {
  const t = normalizeTokens(tokens);
  const axes = modeAxes(tokens);
  const defaults = Object.fromEntries(axes.map((a) => [a.name, a.values[0]]));
  const schemeAxis = axes.find((a) => a.name === 'colorScheme');
  const hasSystem = !!schemeAxis && schemeAxis.values.includes('light') && schemeAxis.values.includes('dark');
  const decl = (layer: TokenOverrides, sel: ModeSelection) => entries(layer).map((e) => `${cssVar(e.path)}: ${cssValue(t, e, sel)};`);
  let css = `/* ${HEADER('tokens')} */\n/* Import once in the app entry. Modes: <html data-ui-${axes.map((a) => kebab(a.name)).join('="…" data-ui-') || 'mode'}="…">, set by setMode() from ./tokens.g. */\n\n`;
  const scheme = (v: string) => (v === 'dark' || v === 'light' ? [`color-scheme: ${v};`] : []);
  css += block(':root', [...(schemeAxis ? scheme(schemeAxis.values[0]) : []), ...decl(t.semantic, defaults)]);
  for (const a of axes) for (const value of a.values.slice(1)) {
    const sel = { ...defaults, [a.name]: value };
    const lines = [...(a.name === 'colorScheme' ? scheme(value) : []), ...decl((t.modes ?? {})[a.name][value], sel)];
    css += '\n' + block(`[data-ui-${kebab(a.name)}="${value}"]`, lines);
    if (a.name === 'colorScheme' && value === 'dark' && hasSystem)
      css += '\n' + `@media (prefers-color-scheme: dark) {\n${block(':root:not([data-ui-color-scheme]), [data-ui-color-scheme="system"]', lines, '  ')}}\n`;
  }
  return css;
}

/** ui/tokens.g.ts: typed accessors, alpha(), setMode / getMode / onModeChange, modeScript. */
export function tokensTs(tokens: ProjectTokens): string {
  const t = normalizeTokens(tokens);
  const axes = modeAxes(tokens);
  const defaults = resolveTheme(tokens).theme;
  const v = (path: string) => `'var(${cssVar(path)})'`;
  const obj = (o: Record<string, unknown>, prefix: string) => `{ ${Object.keys(o).map((k) => `${/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)}: ${v(`${prefix}.${k}`)}`).join(', ')} }`;
  const comp = Object.entries(t.semantic.component ?? {}).map(([c, vs]) => `${c}: ${obj(vs, `component.${c}`)}`).join(', ');
  const modeType = axes.map((a) => `  ${a.name}: ${[...a.values, ...(a.name === 'colorScheme' && a.values.includes('light') && a.values.includes('dark') ? ['system'] : [])].map((x) => `'${x}'`).join(' | ')};`).join('\n');
  const modeDefaults = Object.fromEntries(axes.map((a) => [a.name, a.name === 'colorScheme' && a.values.includes('light') && a.values.includes('dark') ? 'system' : a.values[0]]));
  return `// ${HEADER('tokens')}
// Every value is a CSS custom property from ./tokens.css, so a mode switch restyles without a render.
// Use tokens.* in styles; alpha(tokens.color.primary, 0.12) for translucent colors; values.* only where a number is
// unavoidable (canvas, charts), and redraw on onModeChange().

export const tokens = {
  color: ${obj(t.semantic.color, 'color')},
  space: [${t.semantic.space.map((_, i) => v(`space.${i}`)).join(', ')}],
  radius: ${obj(t.semantic.radius, 'radius')},
  size: ${obj(t.semantic.size ?? {}, 'size')},
  font: ${obj(t.semantic.font, 'font')},
  component: { ${comp} },
} as const;

/** Resolved values of the default mode (numbers, hex): for code that cannot use a CSS variable. */
export const values = ${JSON.stringify(defaults)} as const;

/** spacing step: sp(4) → var(--ui-space-4) */
export const sp = (step: number | string): string => tokens.space[Math.min(Number(step), tokens.space.length - 1)] ?? tokens.space[0];
export const font = (which: keyof typeof tokens.font): string => tokens.font[which];
/** A token color at an opacity: alpha(tokens.color.primary, 0.12) → color-mix(in srgb, var(--ui-color-primary) 12%, transparent) */
export const alpha = (color: string, opacity: number): string => \`color-mix(in srgb, \${color} \${Math.round(opacity * 100)}%, transparent)\`;

export interface Mode {
${modeType}
}
export const defaultMode: Mode = ${JSON.stringify(modeDefaults)};
const KEY = 'ui-mode';
const attr = (axis: string) => 'data-ui-' + axis.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const listeners = new Set<(mode: Mode) => void>();

/** Current mode: what setMode() last applied, else the defaults (colorScheme 'system' follows the OS). */
export function getMode(): Mode {
  if (typeof document === 'undefined') return { ...defaultMode };
  const root = document.documentElement;
  return Object.fromEntries(Object.entries(defaultMode).map(([axis, d]) => [axis, root.getAttribute(attr(axis)) ?? d])) as unknown as Mode;
}

/** Switch one or more axes: setMode({ colorScheme: 'dark' }). Remembered in localStorage unless persist is false. */
export function setMode(mode: Partial<Mode>, options: { persist?: boolean } = {}): void {
  if (typeof document === 'undefined') return;
  const next = { ...getMode(), ...mode } as Mode;
  for (const [axis, value] of Object.entries(next)) document.documentElement.setAttribute(attr(axis), String(value));
  if (options.persist !== false) { try { localStorage.setItem(KEY, JSON.stringify(next)); } catch { /* storage unavailable */ } }
  listeners.forEach((l) => l(next));
}

/** Called after every setMode(); returns an unsubscribe function. */
export function onModeChange(listener: (mode: Mode) => void): () => void {
  listeners.add(listener);
  return () => { listeners.delete(listener); };
}

/** Put in <head> before the CSS (SSR / Next.js) so a remembered mode applies before the first paint: no flash. */
export const modeScript = \`(function(){try{var m=JSON.parse(localStorage.getItem('\${KEY}')||'{}');for(var k in m)document.documentElement.setAttribute('data-ui-'+k.replace(/([a-z0-9])([A-Z])/g,'$1-$2').toLowerCase(),m[k])}catch(e){}})()\`;
`;
}
