import { defineApp } from '@himz-genui/core';

// The outline: every screen and every component this app uses, by name. Write it first.
// Screen details go in ui-spec/screens/<name>.ts; flows, specs and screen code may only use names listed here.
export default defineApp({
  name: 'Gallery',
  screens: {
    Home: 'Every shipped component, grouped by category',
  },
  components: [
    'Accordion',
    'Alert',
    'Avatar',
    'Badge',
    'BarChart',
    'BottomNav',
    'Breadcrumbs',
    'Button',
    'Card',
    'Carousel',
    'Checkbox',
    'ChipGroup',
    'Combobox',
    'ConfirmDialog',
    'Container',
    'DatePicker',
    'DescriptionList',
    'Divider',
    'Drawer',
    'EmptyState',
    'FileUpload',
    'FormField',
    'Grid',
    'Heading',
    'Icon',
    'IconButton',
    'Image',
    'InfiniteScroll',
    'Inline',
    'Input',
    'LineChart',
    'Link',
    'List',
    'ListItem',
    'Menu',
    'Modal',
    'NumberInput',
    'Pagination',
    'PieChart',
    'PinInput',
    'ProgressBar',
    'PullToRefresh',
    'RadioGroup',
    'Rating',
    'SearchBox',
    'SectionHeader',
    'SegmentedControl',
    'Select',
    'Sidebar',
    'Skeleton',
    'Slider',
    'Spacer',
    'Spinner',
    'Stack',
    'Stat',
    'Stepper',
    'SwipeActions',
    'Switch',
    'Table',
    'Tabs',
    'Tag',
    'Text',
    'Textarea',
    'Timeline',
    'Toast',
    'Tooltip',
    'TopBar',
    'Video',
    'SiteFooter',
    'SiteHeader',
    'AvailabilityCalendar',
    'DateRangePicker',
    'RichText',
    'ImageViewer',
    'HorizontalScroll',
    'FloatingActionButton',
  ],
});
