import { defineComponent, t } from '@himz-genui/core';

// Generated by `fw add` from src/legacy/PriceTag.tsx. Edit freely: this file is yours.
export default defineComponent({
  name: 'PriceTag',
  category: 'composite',
  purpose: 'TODO: what it is for, and what not to use it for.',
  props: {
    amount: t.number(),
    currency: t.enum(['USD', 'EUR']),
    strike: t.boolean().opt(),
  },
  events: {
    click: t.void(),
  },
  rules: [],
  impl: { react: 'src/legacy/PriceTag.tsx' },
});
