// GENERATED by fw from ui-spec/project.ts. Do not edit: every fw command rewrites it.
// ignore_for_file: type=lint

import 'package:flutter/material.dart';
import 'tokens.g.dart';

/// MaterialApp(theme: uiTheme()) in the shell; uiTheme(brightness: Brightness.dark) for a dark variant.
ThemeData uiTheme({Brightness brightness = Brightness.light}) {
  final scheme = ColorScheme.fromSeed(seedColor: UiTokens.colorPrimary, brightness: brightness).copyWith(
    primary: UiTokens.colorPrimary,
    secondary: UiTokens.colorSecondary,
    error: UiTokens.colorDanger,
    surface: brightness == Brightness.light ? UiTokens.colorSurface : null,
    onSurface: brightness == Brightness.light ? UiTokens.colorText : null,
  );
  final shape = RoundedRectangleBorder(borderRadius: BorderRadius.circular(UiTokens.radiusMd));
  return ThemeData(
    colorScheme: scheme,
    fontFamily: UiTokens.fontBody,
    // tokens own the sizes: no invisible 48px tap padding (see MaterialTapTargetSize.shrinkWrap in the contracts)
    materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
    filledButtonTheme: FilledButtonThemeData(style: FilledButton.styleFrom(shape: shape)),
    outlinedButtonTheme: OutlinedButtonThemeData(style: OutlinedButton.styleFrom(shape: shape)),
    textButtonTheme: TextButtonThemeData(style: TextButton.styleFrom(shape: shape)),
    cardTheme: CardThemeData(shape: shape),
    inputDecorationTheme: InputDecorationTheme(border: OutlineInputBorder(borderRadius: BorderRadius.circular(UiTokens.radiusMd))),
  );
}
