// GENERATED by fw from ui-spec/project.ts. Do not edit: every fw command rewrites it.
// ignore_for_file: type=lint

import 'dart:ui' show lerpDouble;
import 'package:flutter/material.dart';

enum UiColorScheme { light, dark }

@immutable
class UiColors {
  const UiColors({required this.primary, required this.onPrimary, required this.secondary, required this.onSecondary, required this.danger, required this.onDanger, required this.success, required this.onSuccess, required this.warning, required this.onWarning, required this.surface, required this.surfaceAlt, required this.text, required this.muted, required this.border, required this.scrim, required this.onScrim, required this.shadow});
  final Color primary;
  final Color onPrimary;
  final Color secondary;
  final Color onSecondary;
  final Color danger;
  final Color onDanger;
  final Color success;
  final Color onSuccess;
  final Color warning;
  final Color onWarning;
  final Color surface;
  final Color surfaceAlt;
  final Color text;
  final Color muted;
  final Color border;
  final Color scrim;
  final Color onScrim;
  final Color shadow;
  static UiColors lerp(UiColors a, UiColors b, double t) => UiColors(primary: Color.lerp(a.primary, b.primary, t)!, onPrimary: Color.lerp(a.onPrimary, b.onPrimary, t)!, secondary: Color.lerp(a.secondary, b.secondary, t)!, onSecondary: Color.lerp(a.onSecondary, b.onSecondary, t)!, danger: Color.lerp(a.danger, b.danger, t)!, onDanger: Color.lerp(a.onDanger, b.onDanger, t)!, success: Color.lerp(a.success, b.success, t)!, onSuccess: Color.lerp(a.onSuccess, b.onSuccess, t)!, warning: Color.lerp(a.warning, b.warning, t)!, onWarning: Color.lerp(a.onWarning, b.onWarning, t)!, surface: Color.lerp(a.surface, b.surface, t)!, surfaceAlt: Color.lerp(a.surfaceAlt, b.surfaceAlt, t)!, text: Color.lerp(a.text, b.text, t)!, muted: Color.lerp(a.muted, b.muted, t)!, border: Color.lerp(a.border, b.border, t)!, scrim: Color.lerp(a.scrim, b.scrim, t)!, onScrim: Color.lerp(a.onScrim, b.onScrim, t)!, shadow: Color.lerp(a.shadow, b.shadow, t)!);
}

@immutable
class UiRadius {
  const UiRadius({required this.sm, required this.md, required this.lg, required this.full});
  final double sm;
  final double md;
  final double lg;
  final double full;
  static UiRadius lerp(UiRadius a, UiRadius b, double t) => UiRadius(sm: lerpDouble(a.sm, b.sm, t)!, md: lerpDouble(a.md, b.md, t)!, lg: lerpDouble(a.lg, b.lg, t)!, full: lerpDouble(a.full, b.full, t)!);
}

@immutable
class UiSizes {
  const UiSizes({required this.controlSm, required this.controlMd, required this.controlLg});
  final double controlSm;
  final double controlMd;
  final double controlLg;
  static UiSizes lerp(UiSizes a, UiSizes b, double t) => UiSizes(controlSm: lerpDouble(a.controlSm, b.controlSm, t)!, controlMd: lerpDouble(a.controlMd, b.controlMd, t)!, controlLg: lerpDouble(a.controlLg, b.controlLg, t)!);
}

@immutable
class UiFonts {
  const UiFonts({required this.body, required this.heading});
  final String body;
  final String heading;
  static UiFonts lerp(UiFonts a, UiFonts b, double t) => UiFonts(body: t < 0.5 ? a.body : b.body, heading: t < 0.5 ? a.heading : b.heading);
}

@immutable
class UiTheme extends ThemeExtension<UiTheme> {
  const UiTheme({required this.color, required this.spacing, required this.radius, required this.size, required this.font});
  final UiColors color;
  /// spacing scale by step; read with space(4)
  final List<double> spacing;
  final UiRadius radius;
  final UiSizes size;
  final UiFonts font;
  /// spacing step, e.g. context.ui.space(4)
  double space(int step) => step < spacing.length ? spacing[step] : spacing.last;

  @override
  UiTheme copyWith({UiColors? color, List<double>? spacing, UiRadius? radius, UiSizes? size, UiFonts? font}) =>
      UiTheme(color: color ?? this.color, spacing: spacing ?? this.spacing, radius: radius ?? this.radius, size: size ?? this.size, font: font ?? this.font);

  @override
  UiTheme lerp(covariant ThemeExtension<UiTheme>? other, double t) {
    if (other is! UiTheme) return this;
    return UiTheme(
      color: UiColors.lerp(color, other.color, t),
      spacing: [for (var i = 0; i < spacing.length; i++) lerpDouble(spacing[i], i < other.spacing.length ? other.spacing[i] : spacing[i], t)!],
      radius: UiRadius.lerp(radius, other.radius, t),
      size: UiSizes.lerp(size, other.size, t),
      font: UiFonts.lerp(font, other.font, t),
    );
  }
}

/// colorScheme: light
const UiTheme _theme0 = UiTheme(
  color: UiColors(primary: Color(0xFF2563EB), onPrimary: Color(0xFFFFFFFF), secondary: Color(0xFF64748B), onSecondary: Color(0xFFFFFFFF), danger: Color(0xFFDC2626), onDanger: Color(0xFFFFFFFF), success: Color(0xFF15803D), onSuccess: Color(0xFFFFFFFF), warning: Color(0xFFB45309), onWarning: Color(0xFFFFFFFF), surface: Color(0xFFFFFFFF), surfaceAlt: Color(0xFFF1F5F9), text: Color(0xFF0F172A), muted: Color(0xFF64748B), border: Color(0xFFE2E8F0), scrim: Color(0xFF0F172A), onScrim: Color(0xFFFFFFFF), shadow: Color(0xFF0F172A)),
  spacing: [0.0, 4.0, 8.0, 12.0, 16.0, 24.0, 32.0, 48.0],
  radius: UiRadius(sm: 4.0, md: 8.0, lg: 16.0, full: 9999.0),
  size: UiSizes(controlSm: 32.0, controlMd: 40.0, controlLg: 48.0),
  font: UiFonts(body: 'Inter', heading: 'Inter'),
);

/// colorScheme: dark
const UiTheme _theme1 = UiTheme(
  color: UiColors(primary: Color(0xFF60A5FA), onPrimary: Color(0xFF0F172A), secondary: Color(0xFF94A3B8), onSecondary: Color(0xFF0F172A), danger: Color(0xFFF87171), onDanger: Color(0xFF0F172A), success: Color(0xFF4ADE80), onSuccess: Color(0xFF0F172A), warning: Color(0xFFFBBF24), onWarning: Color(0xFF0F172A), surface: Color(0xFF0F172A), surfaceAlt: Color(0xFF1E293B), text: Color(0xFFF1F5F9), muted: Color(0xFF94A3B8), border: Color(0xFF334155), scrim: Color(0xFF000000), onScrim: Color(0xFFFFFFFF), shadow: Color(0xFF000000)),
  spacing: [0.0, 4.0, 8.0, 12.0, 16.0, 24.0, 32.0, 48.0],
  radius: UiRadius(sm: 4.0, md: 8.0, lg: 16.0, full: 9999.0),
  size: UiSizes(controlSm: 32.0, controlMd: 40.0, controlLg: 48.0),
  font: UiFonts(body: 'Inter', heading: 'Inter'),
);

/// The token values of one mode combination.
UiTheme uiThemeFor({UiColorScheme colorScheme = UiColorScheme.light}) => switch ((colorScheme,)) {
  (UiColorScheme.light,) => _theme0,
  (UiColorScheme.dark,) => _theme1,
};

/// ThemeData for the shell: MaterialApp(theme: uiTheme(), darkTheme: uiTheme(colorScheme: UiColorScheme.dark)).
ThemeData uiTheme({UiColorScheme colorScheme = UiColorScheme.light}) {
  final t = uiThemeFor(colorScheme: colorScheme);
  final brightness = colorScheme == UiColorScheme.dark ? Brightness.dark : Brightness.light;
  final scheme = ColorScheme(
    brightness: brightness,
    primary: t.color.primary,
    onPrimary: t.color.onPrimary,
    secondary: t.color.secondary,
    onSecondary: t.color.onSecondary,
    error: t.color.danger,
    onError: t.color.onDanger,
    surface: t.color.surface,
    onSurface: t.color.text,
    outline: t.color.border,
    outlineVariant: t.color.border,
  );
  final shape = RoundedRectangleBorder(borderRadius: BorderRadius.circular(t.radius.md));
  return ThemeData(
    colorScheme: scheme,
    scaffoldBackgroundColor: scheme.surface,
    fontFamily: t.font.body,
    extensions: [t],
    // tokens own the sizes: no invisible 48px tap padding (see MaterialTapTargetSize.shrinkWrap in the contracts)
    materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
    filledButtonTheme: FilledButtonThemeData(style: FilledButton.styleFrom(shape: shape)),
    outlinedButtonTheme: OutlinedButtonThemeData(style: OutlinedButton.styleFrom(shape: shape)),
    textButtonTheme: TextButtonThemeData(style: TextButton.styleFrom(shape: shape)),
    cardTheme: CardThemeData(shape: shape),
    inputDecorationTheme: InputDecorationTheme(border: OutlineInputBorder(borderRadius: BorderRadius.circular(t.radius.md))),
  );
}

/// The active token values: context.ui.color.primary, context.ui.space(4), context.ui.radius.md.
extension UiThemeContext on BuildContext {
  UiTheme get ui => Theme.of(this).extension<UiTheme>() ?? _theme0;
}
