// GENERATED by fw from ui-spec/project.ts. Do not edit: every fw command rewrites it.
// ignore_for_file: type=lint

import 'dart:ui' show Color;

abstract final class UiTokens {
  static const Color colorPrimary = Color(0xFF2563EB);
  static const Color colorSecondary = Color(0xFF64748B);
  static const Color colorDanger = Color(0xFFDC2626);
  static const Color colorSuccess = Color(0xFF15803D);
  static const Color colorWarning = Color(0xFFB45309);
  static const Color colorSurface = Color(0xFFFFFFFF);
  static const Color colorText = Color(0xFF0F172A);
  static const Color colorMuted = Color(0xFF64748B);
  static const List<double> spacing = [0, 4, 8, 12, 16, 24, 32, 48];
  /** spacing step, e.g. UiTokens.space(4) */
  static double space(int step) => step < spacing.length ? spacing[step] : spacing.last;
  static const double radiusSm = 4;
  static const double radiusMd = 8;
  static const double radiusLg = 16;
  static const double radiusFull = 9999;
  static const String fontBody = 'Inter';
  static const String fontHeading = 'Inter';
}
